version: '3.8'

services:
  app:
    image: eavfeavf/weather-station-app:latest  # Using image from DockerHub
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - MYSQL_HOST=db
      - MYSQL_USER=vovo
      - MYSQL_PASSWORD=vovo_pass_sql
      - MYSQL_DATABASE=vovo
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vovo
      MYSQL_USER: vovo
      MYSQL_PASSWORD: vovo_pass_sql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initializes the DB schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_natatmo
    environment:
      PMA_HOST: db  # Links to the `db` service
      MYSQL_ROOT_PASSWORD: root_password  # Root password of MySQL
    ports:
      - "8080:80"  # Expose phpMyAdmin on localhost:8080
    depends_on:
      - db

volumes:
  mysql_data:
