#!/bin/bash

echo "Zobrazenie všetkých Docker kontajnerov:"
docker ps -a

echo "Odstránenie všetkých kontajnerov:"
docker rm $(docker ps -a -q)


docker build --no-cache -t eavfeavf/weather-station-app:latest .

docker run -p 5000:5000 eavfeavf/weather-station-app:latest

docker push eavfeavf/weather-station-app:latest
